[project]
name = "django-async-include"
version = "0.8.0"
authors = [
  { name="Diego J. Romero López", email="diegojromerolopez@gmail.com" },
]
description = "A simple application for Django to include (and fetch) asynchronous templates"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["django", "template", "asynchronous", "template_tag"]
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
]
license = { text = "MIT" }
dependencies = [
    "Django>=1.11.4",
    "pycryptodome>=3.10.1"
]

[project.urls]
Homepage = "https://github.com/diegojromerolopez/django-async-include"
Issues = "https://github.com/diegojromerolopez/django-async-include/issues"

[dependency-groups]
dev = [
    "black",
    "coverage",
    "mypy",
    "ruff",
]

[tool.black]
line-length = 120
skip_string_normalization = true

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
line-length = 120

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["async_include.tests", "async_include.tests.*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

